test_that("count2 is correct", {
  tb <- tibble::tibble(x = c(1, 3, 2, 3), y = 1:4)
  tb2 <- dplyr::mutate(tb, n = 3)
  x1 <- count2(tb, x)
  x2 <- count2(tb, x, wt = y)
  x3 <- count2(tb, x, name = "nn")
  expect_message(x4 <- count2(tb2, x, n), "Storing counts in `nn`")
  x5 <- dplyr::select(count2(tb, x, sort = FALSE), -prop)

  y1 <- dplyr::count(tb, x, sort = TRUE) %>% dplyr::mutate(prop = n / sum(n))
  y2 <- dplyr::count(tb, x, wt = y, sort = TRUE) %>% dplyr::mutate(prop = n / sum(n))
  y3 <- dplyr::count(tb, x, name = "nn", sort = TRUE) %>% dplyr::mutate(prop = nn / sum(nn))
  suppressMessages(y4 <- dplyr::count(tb2, x, n, sort = TRUE) %>% dplyr::mutate(prop = nn / sum(nn)))
  expect_identical(x1, y1)
  expect_identical(x2, y2)
  expect_identical(x3, y3)
  expect_identical(x4, y4)
  expect_identical(x5, dplyr::count(tb, x))
})

test_that("vcount is correct", {
  x <- c(1L, 1L, 2L, 2L, 2L, 2L, 3L)
  x1 <- vcount(x)
  x2 <- vcount(x, sort = FALSE)
  x3 <- vcount(x, name = "freq", value_name = "vals")
  tb <- tibble::tibble(value = x)
  y1 <- count2(tb, value)

  expect_message(x4 <- vcount(x, value_name = "n"), "Storing counts in `nn`")
  expect_identical(x1, y1)
  expect_identical(names(x3), c("vals", "freq", "prop"))
  expect_identical(x1$value, c(2L, 1L, 3L))
  expect_identical(x2$value, 1:3)
})
